type: "base"
learning_rate: 0.01
epochs: 1
batch_size: 32

num_clusters_per_class: 3

alphas: [3, 5, 8, 9] 
tail_sizes: [10, 100, 250, 500, 750, 1000]
distance_multpls: [1.50, 1.7, 2.0, 2.3]
negative_fix: "ABS_REC_ACTV" # "VALUE_SHIFT", "ABS_REV_ACTV",   

logger_output: false
train_only: false

log_dir: "./logs/"
saved_models_dir: "./saved_models/"
experiment_data_dir: "./experiment_data/"
emnist_dir: "./downloads/"






