type: base
learning_rate: 0.01
momentum: 0.9
epochs: 1
batch_size: 32
num_clusters_per_class_input: []
num_clusters_per_class_features: []
alphas: [-1]
tail_sizes: [2100, 2200, 2300, 2400, 2500, 2600, 2700, 2800]
distance_multipls: [4.75, 5.0, 5.25, 5.5, 5.75]
negative_fix: ['ORIGINAL']
normalize_factor: NORM-WEIGHTS
logger_output: false
train_only: false
log_dir: ./logs/
saved_models_dir: ./saved_models/
experiment_data_dir: ./experiment_data/
emnist_dir: ./downloads/
thresholds: [0.0001, 0.001, 0.01, 0.1, 0.3, 0.5, 0.7]
