type: base
learning_rate: 0.01
momentum: 0.9
epochs: 1
batch_size: 32
num_clusters_per_class_input: []
num_clusters_per_class_features: []
alphas: [10]
tail_sizes: [3700, 3800, 3900, 4000, 4100, 4200, 4300, 4400]
distance_multipls: [3.5, 3.75, 4.0, 4.25, 4.5]
negative_fix: ['ORIGINAL']
normalize_factor: N-CLASSES
logger_output: false
train_only: false
log_dir: ./logs/
saved_models_dir: ./saved_models/
experiment_data_dir: ./experiment_data/
emnist_dir: ./downloads/
thresholds: [0.0001, 0.001, 0.01, 0.1, 0.3, 0.5, 0.7]
