type: "base" # base, input-cluster feature-cluster
learning_rate: 0.01
momentum: 0.9
epochs: 1
batch_size: 32

num_clusters_per_class_input: []
num_clusters_per_class_features: []

alphas: [-1] 

tail_sizes: [5, 10, 100, 500, 800, 1000, 1200, 1500]
# tail_sizes: [1800, 2000, 2200, 2500, 2800, 3000, 3300]
# tail_sizes: [2, 5, 10, 30, 50, 100]

distance_multipls: [1.1, 1.50, 2.0, 2.5, 3.0 , 4.0]
# distance_multpls: [1.25, 1.5, 1.8, 2.0, 2.3, 2.5,]


negative_fix: ["ABS_REV_ACTV"]
# negative_fix: ["VALUE_SHIFT"] # ["Original"]  ["VALUE_SHIFT"], ["ABS_REV_ACTV"]
# negative_fix: ["ABS_REV_ACTV" , "Original"]  ["VALUE_SHIFT"], ["ABS_REV_ACTV"]

normalize_factor: "N-CLASSES" # NONE, WEIGHTS, N-CLASSES, NORM-WEIGHTS

logger_output: true
train_only: false

log_dir: "./logs/"
saved_models_dir: "./saved_models/"
experiment_data_dir: "./experiment_data/"
emnist_dir: "./downloads/"
