type: base
learning_rate: 0.01
momentum: 0.9
epochs: 1
batch_size: 32
num_clusters_per_class_input: []
num_clusters_per_class_features: []
alphas: [3]
tail_sizes: [4800, 4900, 5000, 5100, 5200, 5300, 5400, 5500]
distance_multipls: [1.6, 1.7, 1.8, 1.9, 2.0, 2.1, 2.2]
negative_fix: ['VALUE_SHIFT']
normalize_factor: NORM-WEIGHTS
logger_output: true
train_only: false
eval_only: true
log_dir: ./logs/
saved_models_dir: ./saved_models/pytorch_models/
saved_network_output_dir: ./saved_models/network_outputs/
experiment_data_dir: ./experiment_data/
emnist_dir: ./downloads/
thresholds: [0.0001, 0.001, 0.01, 0.1, 0.3, 0.5, 0.7]
