type: base
learning_rate: 0.01
momentum: 0.9
epochs: 1
batch_size: 32
num_clusters_per_class_input: []
num_clusters_per_class_features: []
alphas: [5]
tail_sizes: [500, 600, 700, 800, 900, 1000, 1100, 1200]
distance_multipls: [1.1, 1.25, 1.5, 1.75, 2.0]
negative_fix: ['NEGATIVE_VALUE']
normalize_factor: NORM-WEIGHTS
logger_output: false
train_only: false
log_dir: ./logs/
saved_models_dir: ./saved_models/
experiment_data_dir: ./experiment_data/
emnist_dir: ./downloads/
thresholds: [0.0001, 0.001, 0.01, 0.1, 0.3, 0.5, 0.7]
