type: base
learning_rate: 0.01
momentum: 0.9
epochs: 1
batch_size: 32
num_clusters_per_class_input: []
num_clusters_per_class_features: []
alphas: [-1]
tail_sizes: [10, 25, 50, 75, 100, 200, 300, 400]
distance_multipls: [3.5, 3.75, 4.0, 4.25, 4.5]
negative_fix: ['NEGATIVE_VALUE']
normalize_factor: NORM-WEIGHTS
logger_output: true
train_only: false
eval_only: true
log_dir: ./logs/
saved_models_dir: ./saved_models/pytorch_models/
saved_network_output_dir: ./saved_models/network_outputs/
experiment_data_dir: ./experiment_data/
emnist_dir: ./downloads/
thresholds: [0.0001, 0.001, 0.01, 0.1, 0.3, 0.5, 0.7]
