type: input-training-features-cluster
learning_rate: 0.01
momentum: 0.9
epochs: 1
batch_size: 32
num_clusters_per_class_input: [8, 9, 10]
num_clusters_per_class_features: [2, 3, 4]
alphas: [-1]
tail_sizes: [6000]
distance_multipls: [1.3]
negative_fix: NEGATIVE_VALUE
normalize_factor: N-CLASSES
logger_output: true
train_only: false
eval_only: false
log_dir: ./logs/
saved_models_dir: ./saved_models/pytorch_models/
saved_network_output_dir: ./saved_models/network_outputs/
experiment_data_dir: ./experiment_data/
emnist_dir: ./downloads/
thresholds: [0.0001, 0.001, 0.01, 0.1, 0.2, 0.5, 0.7, 1.0]
